### ISSUE TITLE
GET /v1/terminal/readers missing preview param `serial_number`

### ISSUE THREAD

**Issue by naseemkullah** [stripe/openapi#129] opened 2023-08-30 02:52 UTC
[this guy](https://stripe.com/docs/api/terminal/readers/list#list_terminal_reader-serial_number)

I noticed this when using `stripe-node` - not sure how the openapi spec gets updated as it all seems to be done by a bot? Is there a way I could submit a fix?

**Comment by remi-stripe** [comment] 2023-08-30 03:40
@naseemkullah thanks for the report. The problem is that feature is still tagged as "preview" on our end and so it's visible in the docs but not. considered fully public. It's definitely a bug though so I'll work on getting this fixed! I'll close this out for now as this will automatically be fixed once the parameter is properly released publicly!

**Closed by remi-stripe** 2023-08-30 03:40 UTC

**Comment by naseemkullah** [comment] 2023-08-30 11:50
> @naseemkullah thanks for the report. The problem is that feature is still tagged as "preview" on our end and so it's visible in the docs but not. considered fully public. It's definitely a bug though so I'll work on getting this fixed! I'll close this out for now as this will automatically be fixed once the parameter is properly released publicly!

Thanks @remi-stripe - can you keep this open until it's released publicly or that preview features are properly added to types? That will make this easier to track on our end to know when to remove the required type casting. If not is there another issue that could be tracked?

**Comment by naseemkullah** [comment] 2023-08-31 03:35
hi Rémi, not to increase scope of this, but also interested in returned Readers device_deploy_group prop, though that one does not even seem to be in the docs.

**Comment by remi-stripe** [comment] 2023-08-31 16:38
That one is not a public feature so it wouldn't be in our public openapi spec. I'd recommend working with your Stripe contact that gave you access to this feature instead
